Add API checks to dockerized git hooks !!!!

diff --git a/unbrake-api/hooks/pre-commit b/unbrake-api/hooks/pre-commit
--- a/unbrake-api/hooks/pre-commit
+++ b/unbrake-api/hooks/pre-commit
@@ -1,44 +1,39 @@
 #!/bin/sh
 
+imageName="unbrake_backend_development"  # compose project name + service name
+tmpFile="/tmp/unbrake_hook_log"
+
 get_staged_files() {
 	git diff --name-only --cached \
-		| grep unbrake-api \
 		| grep .py \
 		| sed -e 's@unbrake-api/@@g'
 }
 
-run_command(){
-	echo -n "Running $(basename $1)..."
-	get_staged_files > $tmpStagedFiles
+run(){
+	echo -n "Running $1..."
+	get_staged_files | xargs $* > $tmpFile
 
-	if [ -s $tmpStagedFiles ]; then
-		xargs $* &> $tmpOutputFile
-
-		if [ $? = 0 ]; then
-			echo -e " \033[0;32mOK!\033[0m"
-		else
-			echo -e " \033[0;31mFAILED!\033[0m\n"
-			cat $tmpOutputFile
-			echo "\033[0;31mSome check failed :(\033[0m"
-			echo -e "\033[0;33mHave you tried to rebuilding the image? Try look the tool documentation as well!\033[0m"
-			exit 1
-		fi
+	if [ $? = 0 ]; then
+		echo -e " \033[0;32mOK!\033[0m"
 	else
-		echo -e "\nThere's no staged python file to be checked on API..."
-		exit 0
+		echo -e " \033[0;31mFAILED!\033[0m\n"
+		cat $tmpFile
+		echo "Some check failed :("
+		echo -e "\033[0;33mHave you tried to rebuilding the image? Try look the tool documentation as well!\033[0m"
+		exit 1
 	fi
 }
 
-source scripts/scripts_environments
-cd $backendFolder
+cd /app/api
+echo -e "\n==============================================================================="
+echo -e "You're almost committing!!! Just a second, while I run some checks and fixes..."
+echo -e "===============================================================================\n"
 
-echo -e "\n=====================================================================-----"
-echo "You're almost committing!!! Just a second, while I run_command some checks and fixes..."
-echo -e "==========================================================================\n"
-
-run_command autopep8 -i -a -a
-run_command flake8
-run_command pylint
-
-rm -rf $tmpOutputFile
-echo -e "\n\033[0;32mCool! All checks succeeded! Commiting...\033[0m"
+if [ -n "$(get_staged_files)" ]; then
+	run autopep8 -i -a -a
+	run flake8
+	run pylint
+	echo -e "\n\033[0;32mCool! All checks succeeded! Committing...\033[0m\n"
+else
+	echo -e "There's no staged python files to be checked. Committing...\n"
+fi
